### ISSUE TITLE
Rubocop linter not compatible with Ruby < 2.4

### ISSUE THREAD

**Issue by vzamanillo** [Shopify/erb-lint#119]
**Error trace**

```
Exception occured when processing: app/views/books/index.html.erb
undefined method `match?' for ".rubocop.yml":String
Did you mean?  match
/.rvm/gems/ruby-2.3.3/gems/erb_lint-0.0.28/lib/erb_lint/linters/rubocop.rb:150:in `block in base_configs'
```
**Config file**

```
---
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingBlankLines:
        Enabled: false
```
**Possible cause**

`String#match?` and `Regexp#match?` are available from Ruby 2.4 and later only, the min required Ruby version to run the gem is 2.3.0+.

**Possible solution**

Implement a custom definition of Regexp#match? for old Rubies (as Rails and others does) and swap the match expression from `"some_string".match?(/pattern/)` to `/pattern/.match?("some_string")`

```
class Regexp #:nodoc:
  def multiline?
    options & MULTILINE == MULTILINE
  end

  def match?(string, pos = 0)
    !!match(string, pos)
  end unless //.respond_to?(:match?)
end
```
**Related**

https://github.com/rails/rails/issues/32970
