### ISSUE TITLE
Exceptions occur during processing with RuboCop 0.72

### ISSUE THREAD

**Issue by cgriego** [Shopify/erb-lint#130]
```
undefined method `[]' for nil:NilClass
gems/erb_lint-0.0.28/lib/erb_lint/linters/rubocop.rb:111:in `cop_classes'
gems/erb_lint-0.0.28/lib/erb_lint/linters/rubocop.rb:120:in `build_team'
gems/erb_lint-0.0.28/lib/erb_lint/linters/rubocop.rb:70:in `inspect_content'
gems/erb_lint-0.0.28/lib/erb_lint/linters/rubocop.rb:34:in `block in run'
```

RuboCop 0.72 removes Rails cops from the core library. The error occurs when executing this line because `@rubocop_config['Rails']` will be nil.

`elsif @rubocop_config['Rails']['Enabled']`

**Comment by betesh** [comment]
As a workaround, you can add `Rails: Enabled: true` to your .erb-lint.yml:

```
---
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Rails:
        Enabled: true
```

**Comment by kmoo** [comment]
This fixed it for me, just add `require: rubocop-rspec` to the top of your `.erb-lint.yml` file:
```yml
require: rubocop-rspec
---
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
```

Cheers 🍻

**Comment by jhottenstein** [comment]
With rubocop 0.78, I had to follow [this workaround](https://github.com/openstreetmap/openstreetmap-website/issues/2472#issuecomment-568255229) and add the requires to my rubocop_todo.yml

**Comment by afdev82** [comment]
I have the same problem with rubocop 0.85.0, and that workaround doesn't work anymore with this new version...
I have already the following in my `rubocop.yml` and `rubocop_todo.yml` files:

```
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true
```

Any idea?

**Comment by betesh** [comment]
@afdev82 Post a stacktrace and your .erb-lint.yml

**Comment by afdev82** [comment]
This is my stacktrace for one file:

```
Exception occured when processing: lib/templates/erb/scaffold/_form.html.erb
If this file cannot be processed by erb-lint, you can exclude it in your configuration file.
undefined method `reject' for #<RuboCop::Cop::Registry:0x00007fbedf0c3780>
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-0.85.0/lib/rubocop/cop/team.rb:147:in `roundup_relevant_cops'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-0.85.0/lib/rubocop/cop/team.rb:116:in `offenses'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rubocop-0.85.0/lib/rubocop/cop/team.rb:67:in `inspect_file'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/linters/rubocop.rb:71:in `inspect_content'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/linters/rubocop.rb:34:in `block in run'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:26:in `<<'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:26:in `block (2 levels) in descendants'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:14:in `traverse'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:20:in `block in traverse_all'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:19:in `each'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:19:in `traverse_all'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:15:in `traverse'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:20:in `block in traverse_all'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:19:in `each'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:19:in `traverse_all'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:15:in `traverse'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_html-1.0.15/lib/better_html/ast/iterator.rb:27:in `block in descendants'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/linters/rubocop.rb:33:in `each'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/linters/rubocop.rb:33:in `each'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/linters/rubocop.rb:33:in `run'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/runner.rb:25:in `block in run'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/runner.rb:24:in `each'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/runner.rb:24:in `run'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/cli.rb:113:in `block in run_with_corrections'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/cli.rb:111:in `times'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/cli.rb:111:in `run_with_corrections'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/cli.rb:63:in `block in run'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/cli.rb:60:in `each'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/lib/erb_lint/cli.rb:60:in `run'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/erb_lint-0.0.33/exe/erblint:9:in `<top (required)>'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/bin/erblint:23:in `load'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/bin/erblint:23:in `<top (required)>'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/Users/antonio.facciolo/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
```

My `.erb-lint.yml`:
```
---
linters:
  FinalNewline:
    enabled: true
  NoJavascriptTagHelper:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Style/NumericPredicate:
        Enabled: false # TODO
      Style/BlockDelimiters:
        Enabled: false # TODO
      Lint/AssignmentInCondition:
        Enabled: false # TODO
      Naming/VariableName:
        Enabled: false # TODO
      Layout/EndAlignment:
        Enabled: false # TODO
      Style/MultilineTernaryOperator:
        Enabled: false # TODO
      Lint/LiteralAsCondition:
        Enabled: false # TODO
  SelfClosingTag:
    enabled: true
    enforced_style: 'always'
  SpaceAroundErbTag:
    enabled: true
```
