### ISSUE TITLE
Rules breaking the code in .erb files

### ISSUE THREAD

**Issue by RichardsonWTR** [Shopify/erb-lint#222]
I think this gem assumes that every block of Ruby in a `.erb` file is a different Ruby file.  
In my case, I've explicitly disabled some rules, to make this gem not break my code. 

```yml
       Layout/InitialIndentation:
        Enabled: false # This rule removes the "<%" e "<%="  from the code, if enabled.
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false  # This rule removes the "<%" e "<%="  from the code, if enabled.
      Layout/LeadingEmptyLines:
        Enabled: false
```

I suggest 3 options for this:
* These rules should be placed in the readme for ease of acess, telling the users to disable them
* These rules should be disabled by the erb lint gem 
* The erb lint gem souldn't treat every block of Ruby code as a different Ruby file.

**Comment by boardfish** [comment]
In addition, it's also a good idea to disable these cops:

```yml
      # Enabling this adds a frozen string literal magic comment to every block.
      Style/FrozenStringLiteralComment:
        Enabled: false
      # erb_lint reports errors with this cop.
      Style/MultilineTernaryOperator:
        Enabled: false
      # False flags for view files. Components should never see this, though.
      Lint/UselessAssignment:
        Exclude:
          - "app/views/**/*"
      # Empty blocks have utility in views, e.g. for resetting content_for and
      # rendering slots without args.
      Lint/EmptyBlock:
        Enabled: false
```
