### ISSUE TITLE
erb-lint removing opening <%= tag

### ISSUE THREAD

**Issue by markreineck** [Shopify/erb-lint#228]
Using erb_lint (0.0.37)

```
<table class="striped">
  <tbody>
  <tr>
    <% fields.each do |fld| %>
      <td style="font-weight: bold"><%= fld[:title] %></td>
    <% end %>
  </tr>
  <% query.all.each do |row| %>
    <tr>
      <% fields.each do |fld| %>
        <td>
          <%=
            value = row.send(fld[:field])
            value = fld[:format].call(value) if fld[:format]
            value
          %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

```

After running "bundle exec erblint --config .erb-lint.yml --autocorrect --lint-all" you have:

```
<table class="striped">
  <tbody>
  <tr>
    <% fields.each do |fld| %>
      <td style="font-weight: bold"><%= fld[:title] %></td>
    <% end %>
  </tr>
  <% query.all.each do |row| %>
    <tr>
      <% fields.each do |fld| %>
        <td>
value = row.send(fld[:field])
            value = fld[:format].call(value) if fld[:format]
            value
          %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

```

This is my .erb-lint.yml

```
---
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**'
glob: "**/*.{html,text,js}{+*,}.erb"
EnableDefaultLinters: true
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
  RightTrim:
    enabled: false
    enforced_style: '-'
  ErbSafety:
    enabled: true

```
