### ISSUE TITLE
Linter for single/double quotes of html attribute values

### ISSUE THREAD

**Issue by toy** [Shopify/erb-lint#259]
While both single and double quotes [are allowed](https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.2) for attribute values, it would be helpful for common style to have linter to force using only one of those.

```html
<div class="something" data-foo='bar'>
</div>
```

**Comment by camertron** [comment]
You should be able to use Rubocop's rules for this:

```yaml
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      AllCops:
        Enabled: false
      Style/StringLiterals:
        Enabled: true
        EnforcedStyle: double_quotes # or single_quotes
```
