### ISSUE TITLE
Rubocop Layout/CommentIndentation autocorrection can cause wrong ERB

### ISSUE THREAD

**Issue by tjschuck** [Shopify/erb-lint#306]
Consider the following ERB:

```erb
<%# comment syntax 1 %>
<% # comment syntax 2 %>
```

The second line is wrong, and correctly gets caught by erb-lint, failing with `Bad ERB comment syntax. Should be <%# without a space between.`

However, if you also have Rubocop enabled with [Layout/CommentIndentation](https://docs.rubocop.org/rubocop/cops_layout.html#layoutcommentindentation), for example with this erb-lint config:

```yaml
---
EnableDefaultLinters: true
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      AllCops:
        DisabledByDefault: true
      Layout/CommentIndentation:
        Enabled: true
```

The test file above gets corrected to:

```erb
<%# comment syntax 1 %>
# comment syntax 2 %>
```

Which is definitely wrong!

I'm not sure if the only solution is to add `Layout/CommentIndentation` to the list of recommended cops to disable in https://github.com/Shopify/erb-lint#Rubocop or if something better can be done to avoid the problem altogether.
