### ISSUE TITLE
Feature Request: Add Ability to Set "cache dir" in `.erb-lint.yml`

### ISSUE THREAD

**Issue by klondikemarlen** [Shopify/erb-lint#309]
I'd love to keep all the config in one place.
I'm already using the `glob:` option, and I'd love to be able to set the `cache_dir` as well.

e.g. 
Instead of running `bundle exec erblint --lint-all --cache --cache-dir tmp/xxx`
I'd love to be able to set the `cache` and `cache-dir` options in the `.erb-lint.yml` config file.

**Comment by keithlayne** [comment]
Just to unnecessarily pile on, how bout a `cache` section in the config?

```yml
glob: ALLTHETHINGS
cache:
  enabled: true
  dir: cachey-mc-erblint-cache
linters: [] # linting overrated
```
