### ISSUE TITLE
Line with only opening `<%=` gets deleted by Rubocop linter

### ISSUE THREAD

**Issue by TastyPi** [Shopify/erb-lint#326]
If I enable the Rubocop linter then any line that just has `<%=` (and whitespace) gets deleted, e.g.

```html.erb
<%=
  tag.div
%>
```

gets formatted as:

```html.erb
tag.div
%>
```

Here's the config:

.erb-lint.yml:

```yml
exclude:
  - "vendor/**/*"
linters:
  RequireInputAutocomplete:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
```

I can try to trim down our `.rubocop.yml` if needed.
