### ISSUE TITLE
can't get a minimal config file to work

### ISSUE THREAD

**Issue by jjb** [Shopify/erb-lint#347]
i loathe to post this because it's certainly something specific to my environment, but i cannot get erb lint to respect my config file. i know it is reading it because if there's an error in it, it raises an error.

```yml
---
glob: "/app/views/**/*.erb"
EnableDefaultLinters: false
linters:
  FrozenStringLiteralComment:
    enabled: true
```

```console
➔ ls app/views/**/*.erb |wc -l
     116
➔ bundle exec erblint
no files found or given, specify files or config...
```
